Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ANewCop:
  Enabled: false

Layout/LineLength:
  Max: 120

AllCops:
  TargetRubyVersion: 3.0